import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

/**
 * Flat config. `next/core-web-vitals` carries the accessibility and
 * performance rules; the additions below are the ones this codebase cares
 * about specifically.
 */
const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'storage/**',
      '.pgdata/**',
      'drizzle/**',
      // Generated by Next on every build; not ours to lint or edit.
      'next-env.d.ts',
    ],
  },
  {
    rules: {
      // Unused variables are a real signal; an underscore prefix is the
      // explicit way to say "deliberately ignored".
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // `any` erases the type safety the rest of the project depends on.
      '@typescript-eslint/no-explicit-any': 'error',

      // next/image is the right default for content images, but this project
      // runs its own media pipeline: widths, formats and the blurred
      // placeholder are all produced at ingest and delivered through
      // `srcset`, so the optimiser has nothing left to add and would only
      // re-encode already-optimised bytes.
      '@next/next/no-img-element': 'off',
    },
  },
];

export default config;
