import { sql } from 'drizzle-orm';
import {
  bigint,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { mediaKindEnum } from './enums';
import { localeColumn } from './locales';
import { users } from './auth';

/** One responsive/derived rendition produced by the media pipeline. */
export type MediaVariant = {
  /** `thumb` | `preview` | `w320` | `w1280` | `half` | `original` … */
  name: string;
  storageKey: string;
  mimeType: string;
  width: number | null;
  height: number | null;
  byteSize: number;
};

export const mediaAssets = pgTable(
  'media_assets',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    kind: mediaKindEnum('kind').notNull(),

    /**
     * Path within the storage driver. Always generated by us — never derived
     * from the uploaded filename, which is attacker-controlled.
     */
    storageKey: text('storage_key').notNull(),
    /** Determined by magic-byte sniffing, not by the client's header. */
    mimeType: text('mime_type').notNull(),
    byteSize: bigint('byte_size', { mode: 'number' }).notNull(),

    width: integer('width'),
    height: integer('height'),
    durationSeconds: doublePrecision('duration_seconds'),

    /** SHA-256 of the stored bytes; enables dedupe and integrity checks. */
    checksum: text('checksum').notNull(),

    /**
     * Tiny blurred placeholder as a data URI (a few hundred bytes). Inlined
     * into the tour manifest so a scene paints immediately, with no extra
     * request, while the full texture downloads.
     */
    previewDataUri: text('preview_data_uri'),

    /** Retained for display only. Never used to build a filesystem path. */
    originalFilename: text('original_filename'),

    variants: jsonb('variants').$type<MediaVariant[]>().notNull().default(sql`'[]'::jsonb`),

    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('media_assets_storage_key_key').on(t.storageKey),
    index('media_assets_checksum_idx').on(t.checksum),
    index('media_assets_kind_idx').on(t.kind),
  ],
);

/**
 * Accessibility and descriptive text for media, per language.
 *
 * Alt text and captions are content, not chrome — a screen-reader user reading
 * the Arabic tour must hear Arabic alt text.
 */
export const mediaTranslations = pgTable(
  'media_translations',
  {
    mediaId: uuid('media_id')
      .notNull()
      .references(() => mediaAssets.id, { onDelete: 'cascade' }),
    locale: localeColumn(),
    altText: text('alt_text'),
    caption: text('caption'),
    /** Transcript for audio narration; captions track for video. */
    transcript: text('transcript'),
  },
  (t) => [primaryKey({ columns: [t.mediaId, t.locale] })],
);

export type MediaAsset = typeof mediaAssets.$inferSelect;
export type NewMediaAsset = typeof mediaAssets.$inferInsert;
