import type { Readable } from 'node:stream';

/**
 * Storage abstraction.
 *
 * Media bytes never live in Postgres. The database holds metadata and a
 * `storageKey`; this interface owns everything else. Swapping local disk for
 * object storage is a driver change and a configuration change — no domain
 * code, no schema change, no migration.
 */

export type ObjectMeta = {
  contentType: string;
  /** Bytes. Used by drivers that must declare length up front. */
  contentLength?: number;
  /** Set on immutable derivatives so a CDN can cache them indefinitely. */
  cacheControl?: string;
};

export type StoredObject = {
  stream: Readable;
  contentType: string;
  contentLength: number | null;
  /** Strong validator for conditional requests. */
  etag: string | null;
};

export interface StorageDriver {
  readonly name: string;

  put(key: string, body: Buffer, meta: ObjectMeta): Promise<void>;

  get(key: string): Promise<StoredObject | null>;

  delete(key: string): Promise<void>;

  exists(key: string): Promise<boolean>;

  /**
   * A URL the browser can fetch directly, or `null` when the object must be
   * proxied through the application. The local driver returns `null`, because
   * its files live outside the web root by design.
   */
  publicUrl(key: string): string | null;
}

/**
 * Rejects any key that could escape the storage root.
 *
 * Keys are generated by us, never supplied by a client — this is the assertion
 * that the invariant still holds, so a future code path that forgets it fails
 * loudly instead of writing outside the root.
 */
export function assertSafeKey(key: string): void {
  if (
    key.length === 0 ||
    key.length > 512 ||
    key.startsWith('/') ||
    key.includes('..') ||
    key.includes('\\') ||
    key.includes('\0') ||
    !/^[A-Za-z0-9._/-]+$/.test(key)
  ) {
    throw new Error(`Unsafe storage key: ${JSON.stringify(key)}`);
  }
}
