/**
 * Downloads the project's typefaces into the repository.
 *
 * Run once, and again only when a family or weight changes:
 *   node scripts/vendor-fonts.mjs
 *
 * Why vendor rather than use `next/font/google`:
 *
 * `next/font/google` fetches from Google at *build* time. That makes every
 * production build depend on a third party being reachable — a CI runner
 * without egress, a network blip, or rate limiting all turn into a failed
 * build, which is exactly what happened while building this project. Fonts are
 * not a moving dependency; they belong in the repository next to the code that
 * uses them.
 *
 * The generated CSS keeps Google's `unicode-range` blocks, so a browser still
 * downloads only the subsets it actually needs — an Arabic reader never pulls
 * the Cyrillic slice, and a Latin reader never pulls the Arabic one.
 */
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const OUT_DIR = path.resolve('public/fonts');
const CSS_OUT = path.resolve('src/app/fonts.css');

// A modern browser UA, so the API returns woff2 rather than legacy formats.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Fraunces', query: 'Fraunces:opsz,wght@9..144,300..700' },
  { name: 'Amiri', query: 'Amiri:wght@400;700' },
  { name: 'IBM Plex Sans Arabic', query: 'IBM+Plex+Sans+Arabic:wght@300;400;500;600' },
  { name: 'IBM Plex Mono', query: 'IBM+Plex+Mono:wght@400;500' },
];

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/**
 * Fetch with retries.
 *
 * Google Fonts intermittently times out from some networks, and this script is
 * the one place that talks to it. Retrying here is what keeps a transient blip
 * from leaving the repository with half its typefaces.
 */
async function fetchWithRetry(url, attempts = 5) {
  let lastError;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      const response = await fetch(url, {
        headers: { 'User-Agent': UA },
        signal: AbortSignal.timeout(30_000),
      });
      if (!response.ok) throw new Error(`${url} -> ${response.status}`);
      return response;
    } catch (error) {
      lastError = error;
      if (attempt < attempts) {
        const wait = 1000 * 2 ** (attempt - 1);
        process.stdout.write(`  retry ${attempt}/${attempts - 1} in ${wait}ms\n`);
        await new Promise((resolve) => setTimeout(resolve, wait));
      }
    }
  }
  throw lastError;
}

async function fetchCss(query) {
  const url = `https://fonts.googleapis.com/css2?family=${query}&display=swap`;
  return (await fetchWithRetry(url)).text();
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const blocks = [];
  let downloaded = 0;

  for (const family of FAMILIES) {
    process.stdout.write(`· ${family.name}\n`);
    let css = await fetchCss(family.query);

    // Each @font-face carries one woff2 URL and one unicode-range.
    const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map(
      (match) => match[1],
    );

    const seen = new Map();
    for (const url of urls) {
      if (seen.has(url)) continue;
      // Name files after the family plus the upstream basename, so two
      // families cannot collide and re-running is idempotent.
      const upstream = url.split('/').pop().split('?')[0];
      const filename = `${slugify(family.name)}-${upstream}`;
      const localPath = `/fonts/${filename}`;

      const target = path.join(OUT_DIR, filename);
      if (existsSync(target)) {
        // Already vendored: font files are immutable, so a re-run resumes
        // rather than re-downloading everything.
        seen.set(url, localPath);
        continue;
      }

      const bytes = Buffer.from(await (await fetchWithRetry(url)).arrayBuffer());
      await writeFile(target, bytes);
      seen.set(url, localPath);
      downloaded += 1;
    }

    for (const [url, localPath] of seen) {
      css = css.split(url).join(localPath);
    }
    blocks.push(`/* ---- ${family.name} ---- */\n${css.trim()}`);
  }

  const header = `/*
 * Generated by scripts/vendor-fonts.mjs — do not edit by hand.
 *
 * Self-hosted so the build needs no network and no visitor request reaches a
 * third-party font host. The unicode-range blocks are preserved from Google's
 * own CSS, so browsers still fetch only the subsets they need.
 */\n`;

  await writeFile(CSS_OUT, `${header}\n${blocks.join('\n\n')}\n`);
  console.log(`\n✓ ${downloaded} font files -> public/fonts`);
  console.log(`✓ ${path.relative(process.cwd(), CSS_OUT)}`);
}

main().catch((error) => {
  console.error('Font vendoring failed:', error);
  process.exit(1);
});
